- category: potential
  customVariables: []
  description: |-
    Remove Thorntail YAML Configuration Files
    If you migrate your application to JBoss EAP XP 2.0 (or later), and want to ensure its Maven building, running or testing works as expected, remove all Thorntail YAML Configuration Files.
  effort: 1
  labels:
  - konveyor.io/source=thorntail
  - konveyor.io/target=eapxp2
  - JBossEAP
  - Thorntail
  links:
  - title: 'Red Hat JBoss EAP XP Migration Guide: Thorntail Application Maven Project
      Migration'
    url: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html/jboss_eap_xp_upgrade_and_migration_guide/thorntail-application-maven-project-migration_default#migrating-a-thorntail-application-maven-project-into-eap-xp_default
  message: If you migrate your application to JBoss EAP XP 2.0 (or later), and want
    to ensure its Maven building, running or testing works as expected, remove all
    Thorntail YAML Configuration Files.
  ruleID: remove_thorntail_yaml_configuration_files-1
  when:
    builtin.file:
      pattern: project-defaults\.yml
