- ruleID: patternfly-v5-to-patternfly-v6-css-values-00000
  description: 576px should be replaced with 36rem
  effort: 3
  category: potential
  labels:
  - konveyor.io/source=patternfly-v5
  - konveyor.io/target=patternfly-v6
  when:
    builtin.filecontent:
      pattern: 576px
      filePattern: \.(css|scss|j|t)sx?$
  message: |-
    Breakpoint values have changed from pixels to rem units


    Replace `576px` with `36rem`.


    Before:

    ```

    576px

    ```


    After:

    ```

    36rem

    ```
  links:
  - url: https://www.patternfly.org/get-started/upgrade/
    title: PatternFly v6 Upgrade Guide
  customVariables: []
- ruleID: patternfly-v5-to-patternfly-v6-css-values-00010
  description: 768px should be replaced with 48rem
  effort: 3
  category: potential
  labels:
  - konveyor.io/source=patternfly-v5
  - konveyor.io/target=patternfly-v6
  when:
    builtin.filecontent:
      pattern: 768px
      filePattern: \.(css|scss|j|t)sx?$
  message: |-
    Breakpoint values have changed from pixels to rem units
    
    Replace `768px` with `48rem`.
    
    Before:
    ```
    768px
    ```
    
    After:
    ```
    48rem
    ```
  links:
  - url: https://www.patternfly.org/get-started/upgrade/
    title: PatternFly v6 Upgrade Guide
  customVariables: []
- ruleID: patternfly-v5-to-patternfly-v6-css-values-00020
  description: 992px should be replaced with 62rem
  effort: 3
  category: potential
  labels:
  - konveyor.io/source=patternfly-v5
  - konveyor.io/target=patternfly-v6
  when:
    builtin.filecontent:
      pattern: 992px
      filePattern: \.(css|scss|j|t)sx?$
  message: |-
    Breakpoint values have changed from pixels to rem units
    
    Replace `992px` with `62rem`.
    
    Before:
    ```
    992px
    ```
    
    After:
    ```
    62rem
    ```
  links:
  - url: https://www.patternfly.org/get-started/upgrade/
    title: PatternFly v6 Upgrade Guide
  customVariables: []
- ruleID: patternfly-v5-to-patternfly-v6-css-values-00030
  description: 1200px should be replaced with 75rem
  effort: 3
  category: potential
  labels:
  - konveyor.io/source=patternfly-v5
  - konveyor.io/target=patternfly-v6
  when:
    builtin.filecontent:
      pattern: 1200px
      filePattern: \.(css|scss|j|t)sx?$
  message: |-
    Breakpoint values have changed from pixels to rem units
    
    Replace `1200px` with `75rem`.
    
    Before:
    ```
    1200px
    ```
    
    After:
    ```
    75rem
    ```
  links:
  - url: https://www.patternfly.org/get-started/upgrade/
    title: PatternFly v6 Upgrade Guide
  customVariables: []
- ruleID: patternfly-v5-to-patternfly-v6-css-values-00040
  description: 1450px should be replaced with 90.625rem
  effort: 3
  category: potential
  labels:
  - konveyor.io/source=patternfly-v5
  - konveyor.io/target=patternfly-v6
  when:
    builtin.filecontent:
      pattern: 1450px
      filePattern: \.(css|scss|j|t)sx?$
  message: |-
    Breakpoint values have changed from pixels to rem units
    
    Replace `1450px` with `90.625rem`.
    
    Before:
    ```
    1450px
    ```
    
    After:
    ```
    90.625rem
    ```
  links:
  - url: https://www.patternfly.org/get-started/upgrade/
    title: PatternFly v6 Upgrade Guide
  customVariables: []
