- category: potential
  customVariables: []
  description: AWS credential configuration
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/source=eap7
  - konveyor.io/source=eap
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - AWS
  links: []
  message: "\n \n The application contains AWS credential configuration.\n \n "
  ruleID: azure-aws-config-credential-01000
  when:
    or:
    - builtin.filecontent:
        filePattern: ""
        pattern: aws_access_key_id
    - builtin.filecontent:
        filePattern: ""
        pattern: aws_secret_access_key
    - builtin.filecontent:
        filePattern: ""
        pattern: aws.credentials
- category: potential
  customVariables: []
  description: AWS region configuration
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/source=eap7
  - konveyor.io/source=eap
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - AWS
  links: []
  message: "\n \n The application contains AWS region configuration.\n \n "
  ruleID: azure-aws-config-region-02000
  when:
    or:
    - builtin.filecontent:
        filePattern: ""
        pattern: aws.region
    - builtin.filecontent:
        filePattern: ""
        pattern: AWS_REGION
    - builtin.filecontent:
        filePattern: ""
        pattern: AWSRegion
- category: potential
  customVariables: []
  description: AWS S3 configuration
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/source=eap7
  - konveyor.io/source=eap
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - AWS
  links: []
  message: "\n \n The application contains AWS S3 configuration.\n Consider using
    Azure Blob Storage instead.\n \n "
  ruleID: azure-aws-config-s3-03000
  when:
    or:
    - builtin.filecontent:
        filePattern: ""
        pattern: aws.s3
- category: potential
  customVariables: []
  description: Amazon Simple Queue Service configuration
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/source=eap7
  - konveyor.io/source=eap
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - AWS
  links: []
  message: "\n \n The application contains Amazon Simple Queue Service configuration.\n
    Consider using Azure Service Bus instead.\n \n "
  ruleID: azure-aws-config-sqs-04000
  when:
    or:
    - builtin.filecontent:
        filePattern: ""
        pattern: aws.sqs
- category: potential
  customVariables: []
  description: AWS Secrets Manager configuration
  effort: 1
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/source=eap7
  - konveyor.io/source=eap
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - AWS
  links: []
  message: "\n \n The application contains AWS Secrets Manager configuration.\n Consider
    using Azure Key Vault instead.\n \n "
  ruleID: azure-aws-config-secret-manager-05000
  when:
    or:
    - builtin.filecontent:
        filePattern: ""
        pattern: aws.secretsmanager
    - builtin.filecontent:
        filePattern: ""
        pattern: aws-secretsmanager
