- category: potential
  customVariables: []
  description: Explicit Config Server connection info found in configuration file
  effort: 0
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - Spring Cloud Config
  links:
  - title: Remove restricted configurations
    url: http://aka.ms/spring-cloud-to-asa?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json&pivots=sc-standard-tier#remove-restricted-configurations
  - title: Prepare the Spring Cloud Config server
    url: http://aka.ms/spring-cloud-to-asa?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json&pivots=sc-standard-tier#prepare-the-spring-cloud-config-server
  message: "\n \n The application uses a Spring Cloud Config Server connection string.\n\n
    If you are migrating to Azure Spring Apps, the connection info of Config Server
    will be injected upon app start. \n Please remove the connection info from your
    configuration file. Configure the Config Server after creating an Azure Spring
    Apps instance.\n \n "
  ruleID: spring-boot-to-azure-config-server-01000
  tag:
  - Spring Cloud Config
  when:
    builtin.filecontent:
      filePattern: application.*\.(properties|yaml|yml)
      pattern: spring\.config\.import|spring\.cloud\.config\.uri
